"""
job-hunter: sheets.py
Manages the 'Job Hunter' Google Spreadsheet with 4 tabs:

  Sheet 1 — Tracker:       Applied roles with status tracking + dropdown
  Sheet 2 — Pipeline:      Full record of all evaluated roles
  Sheet 3 — Job Postings:  User-pasted URLs for batch evaluation
  Sheet 4 — App Q&A:       Application question answers per role (generated by /apply)

Setup (one-time):
  1. console.cloud.google.com → new project → enable Google Sheets API
  2. Create Service Account → download JSON → save as config/google_creds.json
  3. Share your Google Sheet with the service account email (Editor)
  4. Add to .env:
       GOOGLE_SHEET_ID=your_spreadsheet_id
       GOOGLE_SHEETS_TAB_TRACKER=Tracker          (optional, defaults shown)
       GOOGLE_SHEETS_TAB_PIPELINE=Pipeline
       GOOGLE_SHEETS_TAB_POSTINGS=Job Postings
       GOOGLE_SHEETS_TAB_QA=App Q&A

Usage:
  python scripts/sheets.py --setup              # create sheets, headers, dropdowns
  python scripts/sheets.py --sync-pipeline      # push evaluated roles → Sheet 2
  python scripts/sheets.py --sync-tracker       # push applied roles → Sheet 1
  python scripts/sheets.py --get-pending-urls   # print pending URLs from Sheet 3
  python scripts/sheets.py --mark-evaluated URL # mark URL as evaluated in Sheet 3
  python scripts/sheets.py --update-status URL STATUS  # update Tracker status
  python scripts/sheets.py --sync-qa COMPANY TITLE ANSWERS_JSON  # push Q&A → Sheet 4
"""

import json
import os
import sys
import argparse
from pathlib import Path
from datetime import date

try:
    from google.oauth2.service_account import Credentials
    from googleapiclient.discovery import build
    from dotenv import load_dotenv
except ImportError:
    print("❌ Missing dependencies. Run:")
    print("   uv pip install google-auth google-auth-httplib2 google-api-python-client python-dotenv")
    sys.exit(1)

ROOT = Path(__file__).parent.parent
PIPELINE_FILE = ROOT / "pipeline" / "pipeline.json"
CREDS_FILE = ROOT / "config" / "google_creds.json"

load_dotenv(ROOT / ".env")
SHEET_ID = os.getenv("GOOGLE_SHEET_ID")
TAB_TRACKER  = os.getenv("GOOGLE_SHEETS_TAB_TRACKER",  "Tracker")
TAB_PIPELINE = os.getenv("GOOGLE_SHEETS_TAB_PIPELINE", "Pipeline")
TAB_POSTINGS = os.getenv("GOOGLE_SHEETS_TAB_POSTINGS", "Job Postings")
TAB_QA       = os.getenv("GOOGLE_SHEETS_TAB_QA",       "App Q&A")

SCOPES = ["https://www.googleapis.com/auth/spreadsheets"]

# ── Column definitions ────────────────────────────────────────────────────────

TRACKER_HEADERS  = ["Company", "Job Title", "Status", "Application Date", "URL", "Location"]
TRACKER_COLS     = ["company", "job_title", "status", "application_date", "url", "location"]
TRACKER_STATUSES = ["Queued", "Sent", "First Screening", "Interview", "Case Study", "Rejected", "Silent Rejection", "Offer"]

PIPELINE_HEADERS = ["Company", "Job Title", "Tier", "Match Score", "Evaluated Date", "Location", "URL", "Notes"]
PIPELINE_COLS    = ["company", "job_title", "tier", "match_score", "evaluated_date", "location", "url", "notes"]

POSTINGS_HEADERS = ["URL", "Company", "Job Title", "Date Added", "Status"]
POSTINGS_STATUSES = ["Pending", "Manual Retrieval", "Evaluated", "Skipped"]

QA_HEADERS = [
    "Company", "Job Title", "Tier", "Date",
    "Salary (free text)", "Salary (number)",
    "Why this company", "Note to hiring manager", "Anything additional"
]


# ── Auth ──────────────────────────────────────────────────────────────────────

def get_service():
    if not CREDS_FILE.exists():
        print(f"❌ Google credentials not found at {CREDS_FILE}")
        print("   See setup instructions at the top of this file.")
        sys.exit(1)
    if not SHEET_ID:
        print("❌ GOOGLE_SHEET_ID not set in .env")
        sys.exit(1)
    creds = Credentials.from_service_account_file(str(CREDS_FILE), scopes=SCOPES)
    service = build("sheets", "v4", credentials=creds)
    return service.spreadsheets()


def load_pipeline():
    if not PIPELINE_FILE.exists():
        return []
    with open(PIPELINE_FILE) as f:
        return json.load(f)


# ── Sheet ID lookup ───────────────────────────────────────────────────────────

def get_sheet_ids(sheets):
    """Return {tab_name: sheet_id} for all tabs in the spreadsheet."""
    meta = sheets.get(spreadsheetId=SHEET_ID).execute()
    return {s["properties"]["title"]: s["properties"]["sheetId"]
            for s in meta["sheets"]}


# ── Setup ─────────────────────────────────────────────────────────────────────

def setup(sheets):
    """Create sheets, delete default Sheet1, write headers, add bold/freeze/dropdowns/colours."""
    existing = get_sheet_ids(sheets)
    add_requests = []

    # Ensure all 4 tabs exist
    for tab in [TAB_TRACKER, TAB_PIPELINE, TAB_POSTINGS, TAB_QA]:
        if tab not in existing:
            add_requests.append({"addSheet": {"properties": {"title": tab}}})

    if add_requests:
        sheets.batchUpdate(spreadsheetId=SHEET_ID, body={"requests": add_requests}).execute()
        print(f"  Created {len(add_requests)} new sheet(s).")
        existing = get_sheet_ids(sheets)  # refresh

    # Delete the blank default "Sheet1" Google creates automatically
    our_tabs = {TAB_TRACKER, TAB_PIPELINE, TAB_POSTINGS, TAB_QA}
    for name, sid in list(existing.items()):
        if name not in our_tabs and name.lower() in ("sheet1", "sheet 1"):
            sheets.batchUpdate(
                spreadsheetId=SHEET_ID,
                body={"requests": [{"deleteSheet": {"sheetId": sid}}]}
            ).execute()
            print(f"  Deleted blank default sheet: '{name}'")
            break

    # Write headers
    header_map = {
        TAB_TRACKER:  TRACKER_HEADERS,
        TAB_PIPELINE: PIPELINE_HEADERS,
        TAB_POSTINGS: POSTINGS_HEADERS,
        TAB_QA:       QA_HEADERS,
    }
    for tab, headers in header_map.items():
        sheets.values().update(
            spreadsheetId=SHEET_ID,
            range=f"{tab}!A1",
            valueInputOption="RAW",
            body={"values": [headers]}
        ).execute()

    tracker_id  = existing[TAB_TRACKER]
    pipeline_id = existing[TAB_PIPELINE]
    postings_id = existing[TAB_POSTINGS]
    qa_id       = existing[TAB_QA]

    def rgb(r, g, b):
        return {"red": r / 255, "green": g / 255, "blue": b / 255}

    fmt_requests = []

    # Ensure data rows are not bold, then bold only the header row; freeze row 1
    for sid in [tracker_id, pipeline_id, postings_id, qa_id]:
        fmt_requests += [
            {
                "repeatCell": {
                    "range": {"sheetId": sid, "startRowIndex": 1, "endRowIndex": 2000},
                    "cell": {"userEnteredFormat": {"textFormat": {"bold": False}}},
                    "fields": "userEnteredFormat.textFormat.bold"
                }
            },
            {
                "repeatCell": {
                    "range": {"sheetId": sid, "startRowIndex": 0, "endRowIndex": 1},
                    "cell": {"userEnteredFormat": {"textFormat": {"bold": True}}},
                    "fields": "userEnteredFormat.textFormat.bold"
                }
            },
            {
                "updateSheetProperties": {
                    "properties": {"sheetId": sid, "gridProperties": {"frozenRowCount": 1}},
                    "fields": "gridProperties.frozenRowCount"
                }
            }
        ]

    # Dropdown validation
    fmt_requests += [
        {
            "setDataValidation": {
                "range": {
                    "sheetId": tracker_id,
                    "startRowIndex": 1, "endRowIndex": 1000,
                    "startColumnIndex": 2, "endColumnIndex": 3
                },
                "rule": {
                    "condition": {
                        "type": "ONE_OF_LIST",
                        "values": [{"userEnteredValue": s} for s in TRACKER_STATUSES]
                    },
                    "showCustomUi": True,
                    "strict": True
                }
            }
        },
        {
            "setDataValidation": {
                "range": {
                    "sheetId": postings_id,
                    "startRowIndex": 1, "endRowIndex": 1000,
                    "startColumnIndex": 4, "endColumnIndex": 5
                },
                "rule": {
                    "condition": {
                        "type": "ONE_OF_LIST",
                        "values": [{"userEnteredValue": s} for s in POSTINGS_STATUSES]
                    },
                    "showCustomUi": True,
                    "strict": False
                }
            }
        }
    ]

    # ── Conditional formatting ────────────────────────────────────────────────
    # Row-level rules added first (lower priority); cell rules added after
    # (each "index: 0" insert shifts previous rules down, so later = higher priority)

    # Tracker: grey out entire row for Rejected and Silent Rejection
    for formula, bg in [
        ('=$C2="Silent Rejection"', rgb(245, 245, 245)),  # very light grey
        ('=$C2="Rejected"',         rgb(224, 224, 224)),  # medium grey
    ]:
        fmt_requests.append({
            "addConditionalFormatRule": {
                "rule": {
                    "ranges": [{
                        "sheetId": tracker_id,
                        "startRowIndex": 1, "endRowIndex": 1000,
                        "startColumnIndex": 0, "endColumnIndex": 6
                    }],
                    "booleanRule": {
                        "condition": {
                            "type": "CUSTOM_FORMULA",
                            "values": [{"userEnteredValue": formula}]
                        },
                        "format": {"backgroundColor": bg}
                    }
                },
                "index": 0
            }
        })

    # Tracker: status cell colours (col C — added after row rules → higher priority)
    tracker_cell_colors = [
        ("Queued",           rgb(178, 235, 242)),  # turquoise
        ("Sent",             rgb(252, 228, 236)),  # pink
        ("First Screening",  rgb(255, 249, 196)),  # yellow
        ("Interview",        rgb(187, 222, 251)),  # blue
        ("Case Study",       rgb(255, 224, 178)),  # orange
        ("Rejected",         rgb(255, 205, 210)),  # red
        ("Silent Rejection", rgb(189, 189, 189)),  # dark grey
        ("Offer",            rgb(200, 230, 201)),  # green
    ]
    for status, color in tracker_cell_colors:
        fmt_requests.append({
            "addConditionalFormatRule": {
                "rule": {
                    "ranges": [{
                        "sheetId": tracker_id,
                        "startRowIndex": 1, "endRowIndex": 1000,
                        "startColumnIndex": 2, "endColumnIndex": 3
                    }],
                    "booleanRule": {
                        "condition": {
                            "type": "TEXT_EQ",
                            "values": [{"userEnteredValue": status}]
                        },
                        "format": {"backgroundColor": color}
                    }
                },
                "index": 0
            }
        })

    # Job Postings: status cell colours (col E = index 4)
    postings_cell_colors = [
        ("Pending",   rgb(255, 249, 196)),  # yellow
        ("Manual Retrieval", rgb(255, 224, 178)), # orange
        ("Skipped",   rgb(255, 205, 210)),  # red
        ("Evaluated", rgb(200, 230, 201)),  # green
    ]
    for status, color in postings_cell_colors:
        fmt_requests.append({
            "addConditionalFormatRule": {
                "rule": {
                    "ranges": [{
                        "sheetId": postings_id,
                        "startRowIndex": 1, "endRowIndex": 1000,
                        "startColumnIndex": 4, "endColumnIndex": 5
                    }],
                    "booleanRule": {
                        "condition": {
                            "type": "TEXT_EQ",
                            "values": [{"userEnteredValue": status}]
                        },
                        "format": {"backgroundColor": color}
                    }
                },
                "index": 0
            }
        })

    sheets.batchUpdate(spreadsheetId=SHEET_ID, body={"requests": fmt_requests}).execute()
    _apply_pipeline_row_colors(sheets, pipeline_id)

    print(f"✅ Setup complete.")
    print(f"   Sheet 1 — {TAB_TRACKER}:  {len(TRACKER_HEADERS)} columns + dropdown + colour coding + row highlights")
    print(f"   Sheet 2 — {TAB_PIPELINE}: {len(PIPELINE_HEADERS)} columns")
    print(f"   Sheet 3 — {TAB_POSTINGS}: {len(POSTINGS_HEADERS)} columns + dropdown + colour coding")
    print(f"   Sheet 4 — {TAB_QA}:       {len(QA_HEADERS)} columns")
    print(f"\n🔗 https://docs.google.com/spreadsheets/d/{SHEET_ID}")


# ── Formatting helpers ────────────────────────────────────────────────────────

def _apply_pipeline_row_colors(sheets, pipeline_sheet_id):
    """Add row-level conditional formatting to Pipeline by Tier value (column C)."""
    def rgb(r, g, b):
        return {"red": r / 255, "green": g / 255, "blue": b / 255}

    tier_colors = [
        ("skip", rgb(255, 205, 210)),  # red
        ("1",    rgb(200, 230, 201)),  # green
        ("2",    rgb(255, 249, 196)),  # yellow
        ("3",    rgb(255, 224, 178)),  # orange
    ]
    reqs = []
    for value, color in tier_colors:
        reqs.append({
            "addConditionalFormatRule": {
                "rule": {
                    "ranges": [{
                        "sheetId": pipeline_sheet_id,
                        "startRowIndex": 1, "endRowIndex": 2000,
                        "startColumnIndex": 0, "endColumnIndex": 8
                    }],
                    "booleanRule": {
                        "condition": {
                            "type": "CUSTOM_FORMULA",
                            "values": [{"userEnteredValue": f'=$C2="{value}"'}]
                        },
                        "format": {"backgroundColor": color}
                    }
                },
                "index": 0
            }
        })
    sheets.batchUpdate(spreadsheetId=SHEET_ID, body={"requests": reqs}).execute()


def _unformat_data_rows(sheets, sheet_id):
    """Strip bold from data rows on a single sheet (Google inherits header bold on append)."""
    sheets.batchUpdate(spreadsheetId=SHEET_ID, body={"requests": [{
        "repeatCell": {
            "range": {"sheetId": sheet_id, "startRowIndex": 1, "endRowIndex": 2000},
            "cell": {"userEnteredFormat": {"textFormat": {"bold": False}}},
            "fields": "userEnteredFormat.textFormat.bold"
        }
    }]}).execute()


def delete_medium_column(sheets):
    """Delete the Medium column (column E, index 4) from the Tracker sheet.
    One-time migration — run once after removing Medium from TRACKER_HEADERS.
    """
    sheet_ids = get_sheet_ids(sheets)
    tracker_id = sheet_ids[TAB_TRACKER]
    sheets.batchUpdate(spreadsheetId=SHEET_ID, body={"requests": [{
        "deleteDimension": {
            "range": {
                "sheetId": tracker_id,
                "dimension": "COLUMNS",
                "startIndex": 4,  # column E (0-indexed) = "Medium"
                "endIndex": 5
            }
        }
    }]}).execute()
    print("✅ Deleted Medium column (E) from Tracker sheet.")
    print("   Column order is now: Company | Job Title | Status | Application Date | URL | Location")


def fix_data_bold(sheets):
    """Remove bold from all data rows on all sheets (--fix-bold command)."""
    existing = get_sheet_ids(sheets)
    for tab in [TAB_TRACKER, TAB_PIPELINE, TAB_POSTINGS]:
        if tab in existing:
            _unformat_data_rows(sheets, existing[tab])
    print("✅ Removed bold from all data rows.")


def apply_submitted_grayout(sheets):
    """Write live COUNTIFS formulas to Pipeline column I and add a conditional format rule.

    Column I formula (per row):
        =COUNTIFS(Tracker!A:A, A{n}, Tracker!B:B, B{n}, Tracker!C:C, "<>Queued") > 0

    This evaluates to TRUE whenever the matching Tracker row has status != "Queued",
    so rows grey out automatically when the user updates the Tracker — no re-run needed.
    Conditional format rule: =$I2=TRUE → dark grey (index 0 = highest priority).

    Safe to run multiple times — formulas overwrite in place. Each run adds one new
    conditional format rule at index 0; run --fix-pipeline-formatting to clean up
    accumulated rules if needed.
    """
    def rgb(r, g, b):
        return {"red": r / 255, "green": g / 255, "blue": b / 255}

    def tab_ref(name):
        return f"'{name}'" if " " in name else name

    # 1. Find how many data rows are in Pipeline
    try:
        result = sheets.values().get(
            spreadsheetId=SHEET_ID, range=f"{TAB_PIPELINE}!A2:A"
        ).execute()
        pipeline_rows = result.get("values", [])
    except Exception as e:
        print(f"❌ Could not read Pipeline: {e}")
        return

    if not pipeline_rows:
        print("ℹ Pipeline is empty — nothing to set up.")
        return

    sheet_ids = get_sheet_ids(sheets)
    pipeline_id = sheet_ids[TAB_PIPELINE]

    # 2. Find how many data rows are in Q&A
    try:
        qa_result = sheets.values().get(
            spreadsheetId=SHEET_ID, range=f"{TAB_QA}!A2:A"
        ).execute()
        qa_rows = qa_result.get("values", [])
    except Exception as e:
        print(f"⚠ Could not read Q&A sheet: {e}")
        qa_rows = []

    qa_id = sheet_ids[TAB_QA]
    tracker = tab_ref(TAB_TRACKER)

    # 3. Write COUNTIFS formula to Pipeline column I for every data row
    #    Pipeline: Company=A, Job Title=B → marker in column I (index 8)
    pipeline_last_row = len(pipeline_rows) + 1  # +1 for header
    pipeline_formulas = [
        [f'=COUNTIFS({tracker}!A:A,A{row},{tracker}!B:B,B{row},{tracker}!C:C,"<>Queued")>0']
        for row in range(2, pipeline_last_row + 1)
    ]
    sheets.values().update(
        spreadsheetId=SHEET_ID,
        range=f"{TAB_PIPELINE}!I2:I{pipeline_last_row}",
        valueInputOption="USER_ENTERED",
        body={"values": pipeline_formulas}
    ).execute()

    # 4. Write COUNTIFS formula to Q&A column J for every data row
    #    Q&A: Company=A, Job Title=B → marker in column J (index 9, beyond the 9 data cols A–I)
    if qa_rows:
        qa_last_row = len(qa_rows) + 1
        qa_formulas = [
            [f'=COUNTIFS({tracker}!A:A,A{row},{tracker}!B:B,B{row},{tracker}!C:C,"<>Queued")>0']
            for row in range(2, qa_last_row + 1)
        ]
        sheets.values().update(
            spreadsheetId=SHEET_ID,
            range=f"{TAB_QA}!J2:J{qa_last_row}",
            valueInputOption="USER_ENTERED",
            body={"values": qa_formulas}
        ).execute()

    # 5. Add conditional format rules at index 0 (highest priority) for both sheets
    dark_grey       = rgb(80, 80, 80)
    light_grey_text = rgb(180, 180, 180)

    cf_requests = [
        # Pipeline: =$I2=TRUE
        {
            "addConditionalFormatRule": {
                "rule": {
                    "ranges": [{
                        "sheetId": pipeline_id,
                        "startRowIndex": 1, "endRowIndex": 2000,
                        "startColumnIndex": 0, "endColumnIndex": 9
                    }],
                    "booleanRule": {
                        "condition": {
                            "type": "CUSTOM_FORMULA",
                            "values": [{"userEnteredValue": "=$I2=TRUE"}]
                        },
                        "format": {
                            "backgroundColor": dark_grey,
                            "textFormat": {"foregroundColor": light_grey_text}
                        }
                    }
                },
                "index": 0
            }
        },
        # Q&A: =$J2=TRUE
        {
            "addConditionalFormatRule": {
                "rule": {
                    "ranges": [{
                        "sheetId": qa_id,
                        "startRowIndex": 1, "endRowIndex": 2000,
                        "startColumnIndex": 0, "endColumnIndex": 10
                    }],
                    "booleanRule": {
                        "condition": {
                            "type": "CUSTOM_FORMULA",
                            "values": [{"userEnteredValue": "=$J2=TRUE"}]
                        },
                        "format": {
                            "backgroundColor": dark_grey,
                            "textFormat": {"foregroundColor": light_grey_text}
                        }
                    }
                },
                "index": 0
            }
        }
    ]
    sheets.batchUpdate(spreadsheetId=SHEET_ID, body={"requests": cf_requests}).execute()

    print(f"✅ Live COUNTIFS formulas written:")
    print(f"   Pipeline column I — {len(pipeline_formulas)} rows")
    if qa_rows:
        print(f"   Q&A column J      — {len(qa_formulas)} rows")
    print(f"   Rows grey out automatically when Tracker status changes from 'Queued'.")


# ── Sync Pipeline (Sheet 2) ───────────────────────────────────────────────────

def sync_pipeline(sheets):
    """Upsert all evaluated roles to Sheet 2 — update existing rows, append new ones."""
    pipeline = load_pipeline()
    evaluated = [e for e in pipeline if e.get("status") not in ("discovered",)]

    if not evaluated:
        print("ℹ No evaluated roles in pipeline yet.")
        return

    # Read existing sheet: build url→rownum and (company,title)→rownum maps
    try:
        result = sheets.values().get(
            spreadsheetId=SHEET_ID, range=f"{TAB_PIPELINE}!A2:H"
        ).execute()
        existing_rows = result.get("values", [])
    except Exception:
        existing_rows = []

    url_to_row = {}
    ct_to_row = {}
    for i, row in enumerate(existing_rows):
        row_num = i + 2
        url = row[6].strip() if len(row) > 6 else ""
        company = row[0].strip() if len(row) > 0 else ""
        title = row[1].strip() if len(row) > 1 else ""
        if url:
            url_to_row[url] = row_num
        if company and title:
            ct_to_row[(company.lower(), title.lower())] = row_num

    updates = []
    appends = []
    for e in evaluated:
        row_data = [str(e.get(col, "") or "") for col in PIPELINE_COLS]
        url = e.get("url", "") or ""
        company = (e.get("company", "") or "").lower()
        title = (e.get("job_title", "") or "").lower()

        if url and url in url_to_row:
            updates.append((url_to_row[url], row_data))
        elif (company, title) in ct_to_row:
            updates.append((ct_to_row[(company, title)], row_data))
        else:
            appends.append(row_data)

    for row_num, row_data in updates:
        sheets.values().update(
            spreadsheetId=SHEET_ID,
            range=f"{TAB_PIPELINE}!A{row_num}",
            valueInputOption="RAW",
            body={"values": [row_data]}
        ).execute()

    if appends:
        sheets.values().append(
            spreadsheetId=SHEET_ID,
            range=f"{TAB_PIPELINE}!A1",
            valueInputOption="RAW",
            insertDataOption="INSERT_ROWS",
            body={"values": appends}
        ).execute()

    _unformat_data_rows(sheets, get_sheet_ids(sheets)[TAB_PIPELINE])

    print(f"✅ Pipeline sync: {len(updates)} updated, {len(appends)} added.")
    for row_num, row in updates:
        print(f"   ↻ Row {row_num}: {row[0]} — {row[1]} — Tier {row[2]}")
    for row in appends:
        print(f"   + {row[0]} — {row[1]} — Tier {row[2]}")

    # Keep Job Postings statuses in sync with pipeline tiers
    sync_postings_statuses(sheets)


# ── Sync Tracker (Sheet 1) ────────────────────────────────────────────────────

def sync_tracker(sheets):
    """Push applied roles (status = applied+) to Sheet 1 — Tracker."""
    pipeline = load_pipeline()
    applied_statuses = {"applied", "screening", "interview", "offer", "rejected", "withdrawn", "cv_tailored"}
    applied = [e for e in pipeline if e.get("status") in applied_statuses]

    if not applied:
        print("ℹ No applied roles in pipeline yet.")
        return

    try:
        result = sheets.values().get(
            spreadsheetId=SHEET_ID, range=f"{TAB_TRACKER}!E2:E"
        ).execute()
        existing_urls = {r[0] for r in result.get("values", []) if r}
    except Exception:
        existing_urls = set()

    new_rows = []
    for e in applied:
        if e.get("url") in existing_urls:
            continue
        row = [
            e.get("company", ""),
            e.get("job_title", ""),
            "Queued",  # default — set to Sent after user submits the application
            "",        # application date filled manually when user actually submits
            e.get("url", ""),
            e.get("location", ""),
        ]
        new_rows.append(row)

    if not new_rows:
        print("✅ Tracker sheet already up to date.")
        return

    sheets.values().append(
        spreadsheetId=SHEET_ID,
        range=f"{TAB_TRACKER}!A1",
        valueInputOption="USER_ENTERED",
        insertDataOption="INSERT_ROWS",
        body={"values": new_rows}
    ).execute()
    _unformat_data_rows(sheets, get_sheet_ids(sheets)[TAB_TRACKER])

    print(f"✅ Synced {len(new_rows)} roles to Sheet 1 — {TAB_TRACKER}.")


# ── Update Tracker Status ─────────────────────────────────────────────────────

def update_tracker_status(sheets, url, new_status):
    """Update the status of a specific role in the Tracker by URL."""
    if new_status not in TRACKER_STATUSES:
        print(f"❌ Invalid status '{new_status}'. Valid: {', '.join(TRACKER_STATUSES)}")
        sys.exit(1)

    result = sheets.values().get(
        spreadsheetId=SHEET_ID, range=f"{TAB_TRACKER}!A2:F"
    ).execute()
    rows = result.get("values", [])

    for i, row in enumerate(rows):
        if len(row) > 4 and row[4] == url:
            row_num = i + 2
            sheets.values().update(
                spreadsheetId=SHEET_ID,
                range=f"{TAB_TRACKER}!C{row_num}",
                valueInputOption="USER_ENTERED",
                body={"values": [[new_status]]}
            ).execute()
            print(f"✅ {row[0]} — {row[1]}: status → '{new_status}'")
            return

    print(f"⚠ URL not found in Tracker: {url}")


# ── Job Postings (Sheet 3) ────────────────────────────────────────────────────

def update_pipeline_row(sheets, url):
    """Update an existing Pipeline row by URL with current pipeline.json values."""
    pipeline = load_pipeline()
    entry = next((e for e in pipeline if e.get("url") == url), None)
    if not entry:
        print(f"❌ URL not found in pipeline.json: {url}")
        return

    result = sheets.values().get(
        spreadsheetId=SHEET_ID, range=f"{TAB_PIPELINE}!G2:G"
    ).execute()
    rows = result.get("values", [])
    for i, row in enumerate(rows):
        if row and row[0] == url:
            row_num = i + 2
            new_values = [[str(entry.get(col, "") or "") for col in PIPELINE_COLS]]
            sheets.values().update(
                spreadsheetId=SHEET_ID,
                range=f"{TAB_PIPELINE}!A{row_num}",
                valueInputOption="RAW",
                body={"values": new_values}
            ).execute()
            print(f"✅ Updated Pipeline row {row_num}: {entry['company']} — {entry['job_title']} — Tier {entry['tier']} — {entry['match_score']}/100")
            return

    print(f"⚠ URL not found in Pipeline sheet: {url}")


def get_pending_urls(sheets):
    """Read Sheet 3 and return URLs with status 'pending' or blank."""
    try:
        result = sheets.values().get(
            spreadsheetId=SHEET_ID, range=f"{TAB_POSTINGS}!A2:E"
        ).execute()
    except Exception as e:
        print(f"❌ Could not read {TAB_POSTINGS}: {e}")
        return []

    rows = result.get("values", [])
    pending = []
    for row in rows:
        if not row:
            continue
        url = row[0].strip() if row else ""
        status = row[4].strip() if len(row) > 4 else ""
        if url and status in ("Pending", "pending", ""):
            pending.append(url)

    print(f"Found {len(pending)} pending URL(s) in Sheet 3 — {TAB_POSTINGS}:")
    for url in pending:
        print(f"  {url}")
    return pending


def mark_evaluated(sheets, url):
    """Set status = 'evaluated' for a URL in Sheet 3."""
    result = sheets.values().get(
        spreadsheetId=SHEET_ID, range=f"{TAB_POSTINGS}!A2:E"
    ).execute()
    rows = result.get("values", [])

    for i, row in enumerate(rows):
        if row and row[0].strip() == url:
            row_num = i + 2
            sheets.values().update(
                spreadsheetId=SHEET_ID,
                range=f"{TAB_POSTINGS}!E{row_num}",
                valueInputOption="RAW",
                body={"values": [["Evaluated"]]}
            ).execute()
            print(f"✅ Marked as evaluated: {url}")
            return

    print(f"⚠ URL not found in {TAB_POSTINGS}: {url}")


def mark_manual_retrieval(sheets, url):
    """Set status = 'Manual Retrieval' for a URL in Sheet 3."""
    result = sheets.values().get(
        spreadsheetId=SHEET_ID, range=f"{TAB_POSTINGS}!A2:E"
    ).execute()
    rows = result.get("values", [])

    for i, row in enumerate(rows):
        if row and row[0].strip() == url:
            row_num = i + 2
            sheets.values().update(
                spreadsheetId=SHEET_ID,
                range=f"{TAB_POSTINGS}!E{row_num}",
                valueInputOption="RAW",
                body={"values": [["Manual Retrieval"]]}
            ).execute()
            print(f"✅ Marked as Manual Retrieval: {url}")
            return

    print(f"⚠ URL not found in {TAB_POSTINGS}: {url}")


def mark_skipped_posting(sheets, url):
    """Set status = 'Skipped' for a URL in Sheet 3."""
    result = sheets.values().get(
        spreadsheetId=SHEET_ID, range=f"{TAB_POSTINGS}!A2:E"
    ).execute()
    rows = result.get("values", [])

    for i, row in enumerate(rows):
        if row and row[0].strip() == url:
            row_num = i + 2
            sheets.values().update(
                spreadsheetId=SHEET_ID,
                range=f"{TAB_POSTINGS}!E{row_num}",
                valueInputOption="RAW",
                body={"values": [["Skipped"]]}
            ).execute()
            print(f"✅ Marked as Skipped: {url}")
            return

    print(f"⚠ URL not found in {TAB_POSTINGS}: {url}")


def sync_postings_statuses(sheets):
    """Derive Job Postings status from pipeline.json tier — the canonical source of truth.

    tier = "skip"  → "Skipped"
    tier = 1/2/3   → "Evaluated"
    no tier yet    → leave unchanged (Pending / Manual Retrieval)
    """
    pipeline = load_pipeline()
    url_to_tier = {e["url"]: e.get("tier") for e in pipeline if e.get("url")}

    result = sheets.values().get(
        spreadsheetId=SHEET_ID, range=f"{TAB_POSTINGS}!A2:E"
    ).execute()
    rows = result.get("values", [])

    update_data = []
    for i, row in enumerate(rows):
        if not row:
            continue
        url = row[0].strip()
        current_status = row[4].strip() if len(row) > 4 else ""
        if url not in url_to_tier:
            continue
        tier = url_to_tier[url]
        if tier == "skip":
            new_status = "Skipped"
        elif str(tier) in ("1", "2", "3"):
            new_status = "Evaluated"
        else:
            continue  # tier is None/unknown — don't touch status yet
        if new_status != current_status:
            update_data.append({
                "range": f"{TAB_POSTINGS}!E{i + 2}",
                "values": [[new_status]]
            })

    if not update_data:
        print("✅ Job Postings statuses already up to date.")
        return

    sheets.values().batchUpdate(
        spreadsheetId=SHEET_ID,
        body={"valueInputOption": "RAW", "data": update_data}
    ).execute()
    print(f"✅ Synced {len(update_data)} Job Postings status(es) from pipeline tier.")


def update_postings_dropdown(sheets):
    """Push current POSTINGS_STATUSES list to the Job Postings dropdown validation."""
    sheet_ids = get_sheet_ids(sheets)
    if TAB_POSTINGS not in sheet_ids:
        print(f"❌ Sheet '{TAB_POSTINGS}' not found.")
        return
    postings_id = sheet_ids[TAB_POSTINGS]
    sheets.batchUpdate(
        spreadsheetId=SHEET_ID,
        body={"requests": [{
            "setDataValidation": {
                "range": {
                    "sheetId": postings_id,
                    "startRowIndex": 1, "endRowIndex": 1000,
                    "startColumnIndex": 4, "endColumnIndex": 5
                },
                "rule": {
                    "condition": {
                        "type": "ONE_OF_LIST",
                        "values": [{"userEnteredValue": s} for s in POSTINGS_STATUSES]
                    },
                    "showCustomUi": True,
                    "strict": False
                }
            }
        }]}
    ).execute()
    print(f"✅ Job Postings dropdown updated: {', '.join(POSTINGS_STATUSES)}")


# ── App Q&A (Sheet 4) ─────────────────────────────────────────────────────────

def sync_qa(sheets, company, job_title, answers_json):
    """Push application Q&A answers for one role to Sheet 4.

    answers_json is a JSON string mapping question IDs to answer strings:
    {
      "salary_narrative": "...",
      "salary_number": "...",
      "why_company": "...",
      "note_to_hiring_manager": "...",
      "additional_info": "..."
    }
    """
    try:
        answers = json.loads(answers_json)
    except json.JSONDecodeError as e:
        print(f"❌ Invalid answers JSON: {e}")
        sys.exit(1)

    # Find tier from pipeline
    pipeline = load_pipeline()
    tier = ""
    for e in pipeline:
        if e.get("company", "").lower() == company.lower():
            tier = str(e.get("tier", "") or "")
            break

    row = [
        company,
        job_title,
        tier,
        str(date.today()),
        answers.get("salary_narrative", ""),
        answers.get("salary_number", ""),
        answers.get("why_company", ""),
        answers.get("note_to_hiring_manager", ""),
        answers.get("additional_info", ""),
    ]

    # Find the next row number before appending so we can write the grayout formula
    existing = sheets.values().get(
        spreadsheetId=SHEET_ID, range=f"{TAB_QA}!A:A"
    ).execute()
    new_row_num = len(existing.get("values", [])) + 1  # 1-indexed; append lands here

    sheets.values().append(
        spreadsheetId=SHEET_ID,
        range=f"{TAB_QA}!A1",
        valueInputOption="RAW",
        insertDataOption="INSERT_ROWS",
        body={"values": [row]}
    ).execute()

    # Write COUNTIFS grayout formula to column J for the new row
    tracker = f"'{TAB_TRACKER}'" if " " in TAB_TRACKER else TAB_TRACKER
    formula = f'=COUNTIFS({tracker}!A:A,A{new_row_num},{tracker}!B:B,B{new_row_num},{tracker}!C:C,"<>Queued")>0'
    sheets.values().update(
        spreadsheetId=SHEET_ID,
        range=f"{TAB_QA}!J{new_row_num}",
        valueInputOption="USER_ENTERED",
        body={"values": [[formula]]}
    ).execute()

    _unformat_data_rows(sheets, get_sheet_ids(sheets)[TAB_QA])

    print(f"✅ Q&A synced to Sheet 4 — {TAB_QA}: {company} — {job_title}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="job-hunter Google Sheets sync")
    parser.add_argument("--setup",            action="store_true", help="Create sheets, headers, and dropdowns")
    parser.add_argument("--delete-medium-column",      action="store_true", help="One-time: delete Medium column (E) from Tracker sheet")
    parser.add_argument("--fix-bold",                  action="store_true", help="Remove bold from all data rows")
    parser.add_argument("--fix-pipeline-formatting",   action="store_true", help="Apply tier row colours to Pipeline sheet")
    parser.add_argument("--apply-submitted-grayout",   action="store_true", help="Grey out Pipeline rows where Tracker status is not Queued")
    parser.add_argument("--sync-pipeline",    action="store_true", help="Push evaluated roles to Sheet 2")
    parser.add_argument("--sync-tracker",     action="store_true", help="Push applied roles to Sheet 1")
    parser.add_argument("--get-pending-urls", action="store_true", help="Print pending URLs from Sheet 3")
    parser.add_argument("--mark-evaluated",   metavar="URL",       help="Mark URL as evaluated in Sheet 3")
    parser.add_argument("--update-status",    nargs=2, metavar=("URL", "STATUS"), help="Update Tracker status")
    parser.add_argument("--update-pipeline-row", metavar="URL", help="Update an existing Pipeline row by URL from pipeline.json")
    parser.add_argument("--sync-postings-statuses", action="store_true", help="Derive Job Postings statuses from pipeline tier")
    parser.add_argument("--update-postings-dropdown", action="store_true", help="Push current POSTINGS_STATUSES to Job Postings dropdown")
    parser.add_argument("--sync-qa",          nargs=3, metavar=("COMPANY", "TITLE", "ANSWERS_JSON"),
                        help="Push application Q&A answers to Sheet 4")
    args = parser.parse_args()

    sheets = get_service()

    if args.setup:
        setup(sheets)
    elif args.delete_medium_column:
        delete_medium_column(sheets)
    elif args.fix_bold:
        fix_data_bold(sheets)
    elif args.fix_pipeline_formatting:
        _apply_pipeline_row_colors(sheets, get_sheet_ids(sheets)[TAB_PIPELINE])
        print("✅ Pipeline row colours applied.")
    elif args.apply_submitted_grayout:
        apply_submitted_grayout(sheets)
    elif args.sync_pipeline:
        sync_pipeline(sheets)
    elif args.sync_tracker:
        sync_tracker(sheets)
    elif args.get_pending_urls:
        get_pending_urls(sheets)
    elif args.mark_evaluated:
        mark_evaluated(sheets, args.mark_evaluated)
    elif args.update_status:
        update_tracker_status(sheets, args.update_status[0], args.update_status[1])
    elif args.update_pipeline_row:
        update_pipeline_row(sheets, args.update_pipeline_row)
    elif args.sync_postings_statuses:
        sync_postings_statuses(sheets)
    elif args.update_postings_dropdown:
        update_postings_dropdown(sheets)
    elif args.sync_qa:
        sync_qa(sheets, args.sync_qa[0], args.sync_qa[1], args.sync_qa[2])
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
